version: '2.4'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bmn262252
      MYSQL_DATABASE: teste_service
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
#    volumes:
#      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mysql_data:
